### ISSUE TITLE
I can't list all files in a directory

### ISSUE THREAD

**Issue by dolby44** [st-one-io/node-red-contrib-smb#6] opened 2020-11-10 09:17 UTC
Hello,
I'm trying to list all files of a directory (537 files), but the plugin only shows the 262 first files. I put a catch error node, but no error is thrown.

Another folder containing 484 files shows 280 files.

All files have the same attributes and owner and similar size (11MB for the first folder and 1,5MB for the second)

I don't know if I can check a log somewhere

Thank you for your assistance
Thomas

**Comment by machadotiago** [comment] 2020-11-10 10:05
Hello can you paste your flow here? And also your Windows and Node-Red versions.

**Comment by dolby44** [comment] 2020-11-10 15:05
Hello, thank you for your quick answer

Here is the flow:
[{"id":"8b06af7f.e5acb","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"c51d6cdf.98b3f","type":"inject","z":"8b06af7f.e5acb","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":260,"y":100,"wires":[["df1f5f22.2a581"]]},{"id":"df1f5f22.2a581","type":"SMB","z":"8b06af7f.e5acb","name":"","config":"514b838a.dbfe8c","operation":"read-dir","path":"OUT\\MARKET.MD05.EXPORTTAUX","path_new":"","format":"string","x":260,"y":160,"wires":[["798374c7.89109c"]]},{"id":"798374c7.89109c","type":"debug","z":"8b06af7f.e5acb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":570,"y":160,"wires":[]},{"id":"514b838a.dbfe8c","type":"smb config","z":"","name":"SMB Kyriba","share":"\\\\AX1\\KYRIBA","domain":"workgroup"}]

nodered 1.1.3
Windows Server 2008 R2 for the samba share

**Comment by machadotiago** [comment] 2020-11-29 12:16
Hi, sorry for the delay.
Windows 2008 has SMB v1 and v2, can you check which version is available in your installation This node only supports v2

**Comment by dolby44** [comment] 2020-12-09 16:55
Hello, I checked my server and you're right, it uses samba v1.
I'll try to upgrade to samba v2 and see if it's better.

I have another question about samba in nodered:
is there a way to print owner of the file or creation date of the file ?

thank you so much for your help
Thomas

**Comment by machadotiago** [comment] 2020-12-09 18:25
Unfortunately it is not possible to get the file owner.
I'll close this issue by now (since the problem is actually the SMB version), please feel free to re-open it in case the problem persists.

**Closed by machadotiago** 2020-12-09 18:25 UTC

**Comment by dolby44** [comment] 2021-01-15 16:40
Hello again,
We set up samba v2 and still don't see all files (now 276 over 5192)
Can I check something else ?

Thank you

**Comment by machadotiago** [comment] 2021-01-15 18:07
can you send me your flow?

**Comment by dolby44** [comment] 2021-01-16 21:07
yes, it is still the same:

Here is the flow:
[{"id":"8b06af7f.e5acb","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"c51d6cdf.98b3f","type":"inject","z":"8b06af7f.e5acb","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":260,"y":100,"wires":[["df1f5f22.2a581"]]},{"id":"df1f5f22.2a581","type":"SMB","z":"8b06af7f.e5acb","name":"","config":"514b838a.dbfe8c","operation":"read-dir","path":"OUT\FOLDER","path_new":"","format":"string","x":260,"y":160,"wires":[["798374c7.89109c"]]},{"id":"798374c7.89109c","type":"debug","z":"8b06af7f.e5acb","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":570,"y":160,"wires":[]},{"id":"514b838a.dbfe8c","type":"smb config","z":"","name":"SMB share","share":"\\SERVER\FOLDER","domain":"workgroup"}]

**Comment by machadotiago** [comment] 2021-01-18 13:33
strange, I don't see any problem here in my enviroment. Just tried a filder with 1165 items and it is working perfectly

![image](https://user-images.githubusercontent.com/3775353/104921804-907d2400-5978-11eb-9b27-3130d0d374b2.png)

Can you send me a screenshot of your folder properties AND the node-red debug screen?

**Comment by dolby44** [comment] 2021-01-20 11:30
Hello,
I was using debian 9.11 with node-red 1.1.3

I'm now using debian 10.7 with node-red 1.2.7
and samba works now like a charm.

Thank you very much for your help, you can close the ticket
